### ISSUE TITLE
Perl can't find this module after install

### ISSUE THREAD

**Issue by frankiejol** [drrrho/net-async-webservice-lxd#1]
I tried to install this module using cpanminus and I noticed Perl won't find it afterwards.

```Can't locate Net/Async/WebService/lxd.pm in @INC (you may need to install the Net::Async::WebService::lxd module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl)```

If I manually set this environment variable `export PERL5LIB=/usr/lib/perl5/` then it works. But I would like to install it properly, so I tried to set in BUILD.PL --install-base to /usr/local, /usr/share and many other unsuccessfully. I also tried to remove this line hoping it would find the correct path from somewhere but it didn't work. Can you help me ? Thank you very much

This is Ubuntu 22.04, that has v5.34.0

**Comment by drrrho** [comment]
Ah. My ~/.bashrc contains the line

   PERL5LIB="/usr/lib/perl5/${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;

so I never noticed that problem. From what I understand about Module::Build is that one can call

   perl Build.PL --install_path lib=/usr/share/perl5

to enforce .pm files to go there (respective other file types, such as bin, doc). I will investigate why this does not automatically work on Ubuntu.
